apiVersion: v1
kind: Pod
metadata:
  name: scheduler
spec:
  containers:
  - name: scheduler
    image: dimitrihub/scheduler
#    env:
#        - name: GOMAXPROCS
#          value: "1"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      # limits:
      #   memory: "128Mi"
      #   cpu: "2000m"