apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        target: server
      containers:
      - name: scheduler
        imagePullPolicy: Always 
        image: dimitrihub/benchserver
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          # limits:
          #   memory: "128Mi"
          #   cpu: "4000m"
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8123
